name: introduction
description: introduction carousel widget that takes images and texts and shows them inside a dialog.
homepage: https://github.com/marwakarakiii/introduction
version: 1.0.1

environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/book.png
    - lib/assets/images/chat.png
    - lib/assets/images/image.png
    - lib/assets/images/buy.png